spring:
  application:
    name: emailsender

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/ms_emails
    username: 'coachme'
    password: 'root'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

  sleuth:
    integration:
      enabled: true

  zipkin:
    base-url: http://localhost:9411

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#    addresses: amqps://uvigbyif:R12FKow9Qqoag_FO6PWhx3ZV3T-ZiF8M@jackal.rmq.cloudamqp.com/uvigbyif




